os:
  - linux
  - osx

language: d

sudo: false

addons:
  apt:
    packages:
      - libx11-xcb-dev
      - libxcb-keysyms1-dev
      - libxcb-xtest0-dev

d: 
 - dmd-2.069.0
 - dmd-2.068.2
 - dmd-2.067.1
 - dmd-2.066.1
 - gdc-5.2.0
 - gdc-4.9.3
 - gdc-4.8.2
 - ldc-0.16.1
 - ldc-0.16.0
 - ldc-0.15.1

#GDC is not supported on OS X :(
matrix:
  exclude:
  - os: osx
    d: gdc-5.2.0
  - os: osx
    d: gdc-4.9.3
  - os: osx
    d: gdc-4.8.2

#Let's start an X server!
before_script:
  - export DISPLAY=:99.0
  - sh xvfb_setup.sh

#assume only dmd on linux for the time being
script: 
  - ${DMD} build.d
  - ./build
  - ./main



